name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run linter (example for HTML)
        run: |
          echo "Add your linter here"
          # Наприклад:
          # npm install -g htmlhint
          # htmlhint .

  build:
    runs-on: ubuntu-latest
    needs: linter

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t my-app .

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/anarhushka/my-app:latest .

      - name: Push image
        run: docker push ghcr.io/anarhushka/my-app:latest
