name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run linter
        run: echo "No linter yet"

  build:
    runs-on: ubuntu-latest
    needs: linter

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-app .

  k6-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Run container
        run: docker run -d -p 8080:80 my-app

      - name: Wait for app
        run: sleep 5

      - name: Run smoke test
        run: docker run --rm --network host -v ${{ github.workspace }}:/scripts grafana/k6 run /scripts/smoke-test.js

      - name: Run load test
        run: docker run --rm --network host -v ${{ github.workspace }}:/scripts grafana/k6 run /scripts/load-test.js

      - name: Run stress test
        run: docker run --rm --network host -v ${{ github.workspace }}:/scripts grafana/k6 run /scripts/stress-test.js

  push:
    runs-on: ubuntu-latest
    needs: k6-tests

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/anarhushka/my-app:latest .

      - name: Push image
        run: docker push ghcr.io/anarhushka/my-app:latest
